version: "3"

services:
  radarr4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/portainer/downloads:/downloads
      - /opt/portainer/containers/radarr4k:/config
      - /mnt/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr4k.entrypoints=http"
      - "traefik.http.routers.radarr4k.rule=Host(`radarr4k.${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.radarr4k-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr4k.middlewares=radarr4k-https-redirect"
      - "traefik.http.routers.radarr4k-secure.entrypoints=https"
      - "traefik.http.routers.radarr4k-secure.rule=Host(`radarr4k.${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.radarr4k-secure.tls=true"
      - "traefik.http.routers.radarr4k-secure.service=radarr4k"
      - "traefik.http.services.radarr4k.loadbalancer.server.port=7878"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
