version: "3"

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/portainer/containers/adguard/conf:/opt/adguardhome/conf
      - /opt/portainer/containers/adguard/work:/opt/adguardhome/work
