version: "3"

services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/portainer/downloads:/downloads
      - /opt/portainer/containers/nzbget:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=http"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.nzbget-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nzbget.middlewares=nzbget-https-redirect"
      - "traefik.http.routers.nzbget-secure.entrypoints=https"
      - "traefik.http.routers.nzbget-secure.rule=Host(`nzbget.${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.nzbget-secure.tls=true"
      - "traefik.http.routers.nzbget-secure.service=nzbget"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
