version: '3'

services:
  traefik:
    image: traefik:2.11.2
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - DO_AUTH_TOKEN=${DO_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer/containers/traefik/acme.json:/acme.json
      - /opt/portainer/containers/traefik/config.yml:/config.yml:ro
      - /opt/portainer/containers/traefik/traefik.yml:/traefik.yml:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: "http"
      traefik.http.routers.traefik.rule: "Host(`traefik.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.middlewares.traefik-auth.basicauth.users: "${ADMIN_CREDS}"
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.routers.traefik.middlewares: "traefik-https-redirect"
      traefik.http.routers.traefik-secure.entrypoints: "https"
      traefik.http.routers.traefik-secure.rule: "Host(`traefik.${SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.traefik-secure.middlewares: "traefik-auth"
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: "digitalocean"
      traefik.http.routers.traefik-secure.tls.domains[0].main: "${SUBDOMAIN}.${DOMAIN}"
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.${SUBDOMAIN}.${DOMAIN}"
      traefik.http.routers.traefik-secure.service: "api@internal"

networks:
  proxy:
    external: true